name: MysticFireworkPlugin
version: 1.0
main: com.g2806.MysticRocket.MysticFireworkPlugin
api-version: 1.21
description: Plugin to craft infinite Mystic Rockets for Elytra usage.
commands:
  mysticrocket:
    description: Gives a Mystic Rocket of the specified level.
    usage: /<command> <1|2|3|4>
    aliases: []
permissions:
  mysticrocket.give:
    description: Allows giving Mystic Rockets via command.
    default: op